version: '3'

services:
  nginx:
    container_name: fll-clockapp
    image: fll-clockapp:latest
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "10212:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
